version: "3.7"

services:
  db:
    image: postgres
    container_name: team-management
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=team-management
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis
    command: redis-server --requirepass docker --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - /redis:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local