version: "3.7"

services:
  app:
    build:
      context: .
    container_name: team-management-app
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      
  db:
    image: postgres
    container_name: team-management-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=team-management
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis
    container_name: team-management-redis
    command: redis-server --requirepass docker --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - /redis:/data

volumes:
  pgdata:
    driver: local